version: '3'

services:

  db:
    image: mysql
    container_name: mysql_db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    tty: true
    ports:
      - 3306:3306
    networks:
      - db_net
    volumes:
      - ./.data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: nodedb
      MYSQL_ROOT_PASSWORD: root

  app:
    build: ./server
    container_name: node_server
    entrypoint: dockerize -wait tcp://db:3306 -timeout 30s docker-entrypoint.sh
    restart: always
    tty: true
    ports:
      - 3000:3000
    networks:
      - db_net
      - web_net
    depends_on:
      - db

  web:
    image: nginx
    container_name: web_server
    restart: always
    tty: true
    volumes:
      - ./web:/usr/share/nginx/html
      - ./web/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    networks:
      - web_net

networks:
  db_net:
  web_net:
    driver: bridge
